version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: https://dagshub.com/flaviapaulinos/analise_enem_caxambu.mlflow
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD}

  streamlit:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api