services:
  - type: web
    name: analise-enem
    runtime: image
    repo: https://github.com/flaviapaulinos/analise_enem_caxambu
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10